name: Scape Dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Style Guide enforcement
      run: |
        black --line-length 79 --check --color --diff project/
        isort --profile black -l 79 --check-only --diff project/
        flake8 --statistics --doctests scenario/

    - name: Run Tests
      run: |
        echo "Successful"